import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
const app = await readFile(new URL("../dist/app.js", import.meta.url), "utf8");

for (const profile of ["balanced", "performance", "value"]) {
  assert.match(html, new RegExp(`data-profile="${profile}"`));
}

assert.equal((html.match(/class="profile-button/g) ?? []).length, 3);
assert.match(html, /role="group" aria-label="Recommendation profile"/);
assert.match(app, /recommendBuild\(constraints, activeProfile\)/);
assert.match(app, /setAttribute\("aria-pressed"/);
assert.match(app, /recommendation\.rationales\[type\]/);
assert.match(html, /shows why each component earned its place/);
assert.match(html, /id="copy-build"/);
assert.match(html, /id="copy-validation"/);
assert.match(html, /id="copy-link"/);
assert.match(html, /id="download-build"/);
assert.match(html, /id="import-build"[^>]+type="file"[^>]+accept="application\/json,.json"/);
assert.match(html, /id="import-trigger"/);
assert.match(html, /id="download-markdown"/);
assert.match(html, /id="download-csv"/);
assert.match(html, /id="print-build"/);
assert.match(html, /id="export-status" role="status" aria-live="polite"/);
assert.match(app, /navigator\.clipboard\.writeText/);
assert.match(app, /function buildValidationText\(\)/);
assert.match(app, /Validation report copied/);
assert.match(app, /new Blob/);
assert.match(app, /importInput\.addEventListener\("change", async/);
assert.match(app, /importButton\.addEventListener\("click"/);
assert.match(app, /JSON build plan imported and recalculated/);
assert.match(app, /not a valid AIPO-GPT build plan/);
assert.match(app, /function buildMarkdown\(\)/);
assert.match(app, /function buildCsv\(\)/);
assert.match(app, /text\/csv/);
assert.match(app, /CSV bill of materials downloaded/);
assert.match(app, /text\/markdown/);
assert.match(app, /window\.print\(\)/);
assert.match(html, /<summary>Compare all profiles<\/summary>/);
assert.match(html, /id="profile-comparison-body"/);
assert.match(app, /data-compare-profile/);
assert.match(app, /button\.dataset\.compareProfile/);
assert.match(html, /<th scope="col">Peak draw<\/th>/);
assert.match(html, /<th scope="col">Upgrade<\/th>/);
assert.match(app, /option\.platformWatts/);
assert.match(app, /option\.upgradeReadiness\.score/);
assert.match(html, /id="upgrade-readiness"/);
assert.match(app, /recommendation\.upgradeReadiness\.label/);
assert.match(html, /<summary>Upgrade-readiness breakdown<\/summary>/);
assert.match(html, /id="upgrade-breakdown-list"/);
assert.match(app, /recommendation\.upgradeReadiness\.signals/);
assert.match(html, /id="cooler-noise"/);
assert.match(app, /recommendation\.acoustics\.decibels/);
assert.match(html, /id="power-reserve"/);
assert.match(app, /recommendation\.powerReserve\.percentage/);
assert.match(html, /id="budget-progress" role="progressbar"/);
assert.match(html, /id="budget-usage"/);
assert.match(app, /recommendation\.budgetUsage\.percentage/);
assert.match(html, /id="value-density"/);
assert.match(app, /recommendation\.valueDensity\.pointsPerThousand/);
assert.match(html, /id="goal"[^>]+required minlength="12"/);
assert.match(html, /id="budget"[^>]+required/);
assert.match(html, /id="budget-range"[^>]+type="range"/);
assert.match(app, /fields\.budgetRange\.addEventListener\("input"/);
assert.match(app, /fields\.budget\.addEventListener\("input"/);
assert.match(html, /id="form-error" role="alert"/);
assert.match(app, /form\.addEventListener\("invalid"/);
assert.equal((html.match(/data-preset=/g) ?? []).length, 3);
assert.match(app, /fields\.goal\.value = button\.dataset\.preset/);
assert.match(app, /history\.replaceState/);
assert.match(app, /restoreFromUrl\(syncGoalToFields\(\)\)/);
assert.match(app, /window\.location\.href/);
assert.match(html, /class="skip-link" href="#optimizer-form"/);
assert.match(html, /id="results-heading" tabindex="-1"/);
assert.match(html, /id="result-status" role="status" aria-live="polite"/);
assert.match(app, /render\(syncGoalToFields\(\), \{ announce: true \}\)/);
assert.match(app, /querySelector\("#results-heading"\)\.focus\(\)/);
assert.match(html, /<summary>Where the budget goes<\/summary>/);
assert.match(html, /id="allocation-list"/);
assert.match(app, /recommendation\.budgetAllocation/);
assert.match(html, /id="shortfall-panel" hidden/);
assert.match(html, /id="shortfall-list"/);
assert.match(app, /recommendation\.shortfalls/);
assert.match(html, /<option value="development">Software development<\/option>/);
assert.match(html, /<option value="ai">Local AI \/ machine learning<\/option>/);
assert.match(html, /<option value="upgradeability">Upgrade headroom<\/option>/);
assert.match(app, /"upgradeability"/);
assert.match(html, /id="memory-target"/);
assert.match(html, /<option value="64">At least 64GB<\/option>/);
assert.match(app, /memoryTarget: fields\.memoryTarget\.value/);
assert.match(html, /id="storage-target"/);
assert.match(html, /<option value="2">At least 2TB<\/option>/);
assert.match(app, /storageTarget: fields\.storageTarget\.value/);
assert.match(html, /id="noise-target"/);
assert.match(html, /<option value="24">24dBA — quiet<\/option>/);
assert.match(app, /noiseTarget: fields\.noiseTarget\.value/);
assert.match(html, /id="vram-target"/);
assert.match(html, /<option value="16">At least 16GB VRAM<\/option>/);
assert.match(app, /vramTarget: fields\.vramTarget\.value/);
assert.match(html, /id="core-target"/);
assert.match(html, /<option value="12">At least 12 cores<\/option>/);
assert.match(app, /coreTarget: fields\.coreTarget\.value/);
assert.match(html, /id="power-target"/);
assert.match(html, /<option value="450">450W — efficient<\/option>/);
assert.match(app, /powerTarget: fields\.powerTarget\.value/);
assert.match(html, /id="case-target"/);
assert.match(html, /<option value="compact">Compact<\/option>/);
assert.match(app, /caseTarget: fields\.caseTarget\.value/);
assert.match(html, /id="build-id"/);
assert.match(app, /latestRecommendation\.buildId/);
assert.match(html, /id="search-stats"/);
assert.match(app, /recommendation\.searchStats\.evaluated/);
assert.match(html, /<summary>Runner-up configurations<\/summary>/);
assert.match(html, /id="alternatives-list"/);
assert.match(app, /recommendation\.alternatives/);
assert.match(app, /alternative\.platformWatts/);
assert.match(app, /alternative\.goalsMet/);
assert.match(html, /id="balance-score"/);
assert.match(app, /recommendation\.componentBalance\.score/);
assert.match(html, /id="reset-build"/);
assert.match(app, /DEFAULT_STATE = Object\.freeze/);
assert.match(app, /Optimizer defaults restored/);
assert.match(app, /fields\.goal\.focus\(\)/);
assert.match(html, /id="recovery-path" hidden/);
assert.match(app, /recommendation\.goalRecovery/);
assert.match(app, /meeting every performance target/);
assert.match(html, /id="save-local"/);
assert.match(html, /id="load-local"/);
assert.match(html, /id="clear-local"/);
assert.match(app, /localStorage\.setItem\(SAVED_BUILD_KEY/);
assert.match(app, /function readSavedBuild\(\)/);
assert.match(app, /Build saved in this browser/);
assert.match(app, /Saved build restored/);
assert.match(app, /localStorage\.removeItem\(SAVED_BUILD_KEY\)/);
assert.match(app, /Saved browser build cleared/);
assert.match(html, /id="advanced-controls"/);
assert.match(html, /id="advanced-count">Automatic/);
assert.match(app, /function updateAdvancedCount\(\)/);
assert.match(app, /activeCount === 0 \? "Automatic"/);
assert.match(app, /matchMedia\("\(pointer: fine\)"\)/);
assert.match(app, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
assert.match(app, /requestAnimationFrame/);
assert.match(app, /--pointer-shift-x/);
assert.equal((html.match(/data-workspace-view=/g) ?? []).length, 2);
assert.match(html, /data-mobile-view="configure"/);
assert.match(app, /function setWorkspaceView\(view/);
assert.match(app, /setWorkspaceView\("results"\)/);
assert.match(html, /id="optimize-label">Generate build/);
assert.match(html, /class="results-panel"[^>]+aria-busy="false"/);
assert.match(app, /function signalResultUpdate/);
assert.match(app, /resultsPanel\.setAttribute\("aria-busy", "true"\)/);
assert.match(app, /optimizeLabel\.textContent = "Build ready"/);
assert.match(html, /id="toggle-all-parts">Inspect all/);
assert.match(app, /aria-controls="part-inspection-\$\{type\}"/);
assert.match(app, /function syncPartsToggleLabel\(\)/);
assert.match(app, /toggleAllPartsButton\.addEventListener\("click"/);
assert.match(app, /budgetAllocation\[type\]\.percentage/);
assert.match(html, /id="constraint-chips" aria-label="Active build constraints"/);
assert.match(app, /function renderConstraintChips\(constraints\)/);
assert.match(app, /data-edit-field=/);
assert.match(app, /setWorkspaceView\("configure"\)/);

console.log("UI contract tests passed");
