import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
const app = await readFile(new URL("../dist/app.js", import.meta.url), "utf8");
const css = await readFile(new URL("../dist/styles.css", import.meta.url), "utf8");

for (const profile of ["balanced", "performance", "value"]) {
  assert.match(html, new RegExp(`data-profile="${profile}"`));
}

assert.equal((html.match(/class="profile-button/g) ?? []).length, 3);
assert.match(html, /role="group" aria-label="Recommendation profile"/);
assert.match(app, /recommendBuild\(constraints, activeProfile\)/);
assert.match(app, /setAttribute\("aria-pressed"/);
assert.match(app, /recommendation\.rationales\[type\]/);
assert.match(html, /shows why each component earned its place/);
assert.match(html, /id="copy-build"/);
assert.match(html, /id="copy-validation"/);
assert.match(html, /id="copy-link"/);
assert.match(html, /id="download-build"/);
assert.match(html, /id="import-build"[^>]+type="file"[^>]+accept="application\/json,.json"/);
assert.match(html, /id="import-trigger"/);
assert.match(html, /id="download-markdown"/);
assert.match(html, /id="download-csv"/);
assert.match(html, /id="print-build"/);
assert.match(html, /id="export-status" role="status" aria-live="polite"/);
assert.match(app, /navigator\.clipboard\.writeText/);
assert.match(app, /function buildValidationText\(\)/);
assert.match(app, /Validation report copied/);
assert.match(app, /new Blob/);
assert.match(app, /importInput\.addEventListener\("change", async/);
assert.match(app, /importButton\.addEventListener\("click"/);
assert.match(app, /JSON build plan imported and recalculated/);
assert.match(app, /not a valid AIPO-GPT build plan/);
assert.match(app, /function buildMarkdown\(\)/);
assert.match(app, /function buildCsv\(\)/);
assert.match(app, /text\/csv/);
assert.match(app, /CSV bill of materials downloaded/);
assert.match(app, /text\/markdown/);
assert.match(app, /window\.print\(\)/);
assert.match(html, /<summary>Compare all profiles<\/summary>/);
assert.match(html, /id="profile-comparison-body"/);
assert.match(app, /data-compare-profile/);
assert.match(app, /button\.dataset\.compareProfile/);
assert.match(html, /<th scope="col">Peak draw<\/th>/);
assert.match(html, /<th scope="col">Upgrade<\/th>/);
assert.match(app, /option\.platformWatts/);
assert.match(app, /option\.upgradeReadiness\.score/);
assert.match(html, /id="upgrade-readiness"/);
assert.match(app, /recommendation\.upgradeReadiness\.label/);
assert.match(html, /<summary>Upgrade-readiness breakdown<\/summary>/);
assert.match(html, /id="upgrade-breakdown-list"/);
assert.match(app, /recommendation\.upgradeReadiness\.signals/);
assert.match(html, /id="cooler-noise"/);
assert.match(app, /recommendation\.acoustics\.decibels/);
assert.match(html, /id="power-reserve"/);
assert.match(app, /recommendation\.powerReserve\.percentage/);
assert.match(html, /id="budget-progress" role="progressbar"/);
assert.match(html, /id="budget-usage"/);
assert.match(app, /recommendation\.budgetUsage\.percentage/);
assert.match(html, /id="value-density"/);
assert.match(app, /recommendation\.valueDensity\.pointsPerThousand/);
assert.match(html, /id="goal"[^>]+required minlength="12"/);
assert.match(html, /id="goal-guidance">Ready to parse workload and priorities/);
assert.match(html, /id="goal-count">62 characters/);
assert.match(app, /function updateGoalFeedback\(\)/);
assert.match(app, /Math\.max\(0, 12 - length\)/);
assert.match(app, /fields\.goal\.addEventListener\("input", updateGoalFeedback\)/);
assert.match(html, /id="budget"[^>]+required/);
assert.match(html, /id="budget-range"[^>]+type="range"/);
assert.match(app, /fields\.budgetRange\.addEventListener\("input"/);
assert.match(app, /fields\.budget\.addEventListener\("input"/);
assert.equal((html.match(/data-budget-adjust=/g) ?? []).length, 2);
assert.match(app, /button\.dataset\.budgetAdjust/);
assert.match(app, /Math\.min\(5000, Math\.max\(800/);
assert.match(html, /id="form-error" role="alert"/);
assert.match(app, /form\.addEventListener\("invalid"/);
assert.equal((html.match(/data-preset=/g) ?? []).length, 3);
assert.match(app, /fields\.goal\.value = button\.dataset\.preset/);
assert.match(app, /history\.replaceState/);
assert.match(app, /restoreFromUrl\(syncGoalToFields\(\)\)/);
assert.match(app, /window\.location\.href/);
assert.match(html, /class="skip-link" href="#optimizer-form"/);
assert.match(html, /id="results-heading" tabindex="-1"/);
assert.match(html, /id="result-status" role="status" aria-live="polite"/);
assert.match(app, /render\(syncGoalToFields\(\), \{ announce: true \}\)/);
assert.match(app, /querySelector\("#results-heading"\)\.focus\(\)/);
assert.match(html, /<summary>Where the budget goes<\/summary>/);
assert.match(html, /id="allocation-list"/);
assert.match(app, /recommendation\.budgetAllocation/);
assert.match(html, /id="shortfall-panel" hidden/);
assert.match(html, /id="shortfall-list"/);
assert.match(app, /recommendation\.shortfalls/);
assert.equal((html.match(/data-validation-filter=/g) ?? []).length, 3);
assert.match(html, /id="validation-filter-status" role="status" aria-live="polite"/);
assert.match(app, /function applyValidationFilter\(filter = activeValidationFilter\)/);
assert.match(app, /row\.classList\.contains\("is-warning"\)/);
assert.match(app, /button\.dataset\.validationFilter/);
assert.match(html, /<option value="development">Software development<\/option>/);
assert.match(html, /<option value="ai">Local AI \/ machine learning<\/option>/);
assert.match(html, /<option value="upgradeability">Upgrade headroom<\/option>/);
assert.match(app, /"upgradeability"/);
assert.match(html, /id="memory-target"/);
assert.match(html, /<option value="64">At least 64GB<\/option>/);
assert.match(app, /memoryTarget: fields\.memoryTarget\.value/);
assert.match(html, /id="storage-target"/);
assert.match(html, /<option value="2">At least 2TB<\/option>/);
assert.match(app, /storageTarget: fields\.storageTarget\.value/);
assert.match(html, /id="noise-target"/);
assert.match(html, /<option value="24">24dBA — quiet<\/option>/);
assert.match(app, /noiseTarget: fields\.noiseTarget\.value/);
assert.match(html, /id="vram-target"/);
assert.match(html, /<option value="16">At least 16GB VRAM<\/option>/);
assert.match(app, /vramTarget: fields\.vramTarget\.value/);
assert.match(html, /id="core-target"/);
assert.match(html, /<option value="12">At least 12 cores<\/option>/);
assert.match(app, /coreTarget: fields\.coreTarget\.value/);
assert.match(html, /id="power-target"/);
assert.match(html, /<option value="450">450W — efficient<\/option>/);
assert.match(app, /powerTarget: fields\.powerTarget\.value/);
assert.match(html, /id="case-target"/);
assert.match(html, /<option value="compact">Compact<\/option>/);
assert.match(app, /caseTarget: fields\.caseTarget\.value/);
assert.match(html, /id="build-id"/);
assert.match(app, /latestRecommendation\.buildId/);
assert.match(html, /id="search-stats"/);
assert.match(app, /recommendation\.searchStats\.evaluated/);
assert.match(html, /<summary>Runner-up configurations<\/summary>/);
assert.match(html, /id="alternatives-list"/);
assert.match(app, /recommendation\.alternatives/);
assert.match(app, /alternative\.platformWatts/);
assert.match(app, /alternative\.goalsMet/);
assert.match(html, /id="balance-score"/);
assert.match(app, /recommendation\.componentBalance\.score/);
assert.match(html, /id="reset-build"/);
assert.match(app, /DEFAULT_STATE = Object\.freeze/);
assert.match(app, /Optimizer defaults restored/);
assert.match(app, /fields\.goal\.focus\(\)/);
assert.match(html, /id="recovery-path" hidden/);
assert.match(app, /recommendation\.goalRecovery/);
assert.match(app, /meeting every performance target/);
assert.match(html, /id="save-local"/);
assert.match(html, /id="load-local"/);
assert.match(html, /id="clear-local"/);
assert.match(app, /localStorage\.setItem\(SAVED_BUILD_KEY/);
assert.match(app, /function readSavedBuild\(\)/);
assert.match(app, /Build saved in this browser/);
assert.match(app, /Saved build restored/);
assert.match(app, /localStorage\.removeItem\(SAVED_BUILD_KEY\)/);
assert.match(app, /Saved browser build cleared/);
assert.match(html, /id="advanced-controls"/);
assert.match(html, /id="advanced-count">Automatic/);
assert.match(app, /function updateAdvancedCount\(\)/);
assert.match(app, /activeCount === 0 \? "Automatic"/);
assert.match(app, /matchMedia\("\(pointer: fine\)"\)/);
assert.match(app, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
assert.match(app, /requestAnimationFrame/);
assert.match(app, /--pointer-shift-x/);
assert.equal((html.match(/data-workspace-view=/g) ?? []).length, 2);
assert.match(html, /data-mobile-view="configure"/);
assert.match(app, /function setWorkspaceView\(view/);
assert.match(app, /setWorkspaceView\("results"\)/);
assert.match(html, /id="optimize-label">Generate build/);
assert.match(html, /class="results-panel"[^>]+aria-busy="false"/);
assert.match(app, /function signalResultUpdate/);
assert.match(app, /resultsPanel\.setAttribute\("aria-busy", "true"\)/);
assert.match(html, /class="results-loading-indicator" aria-hidden="true"/);
assert.match(app, /"Generating recommendation"/);
assert.match(css, /@keyframes loading-scan/);
assert.match(css, /\.results-panel\.is-updating \.results-loading-indicator/);
assert.match(app, /optimizeLabel\.textContent = "Build ready"/);
assert.match(html, /id="toggle-all-parts">Inspect all/);
assert.match(app, /aria-controls="part-inspection-\$\{type\}"/);
assert.match(app, /function syncPartsToggleLabel\(\)/);
assert.match(app, /toggleAllPartsButton\.addEventListener\("click"/);
assert.match(html, /id="part-filter" type="search"/);
assert.match(html, /id="part-filter-status" role="status" aria-live="polite"/);
assert.match(app, /function filterParts\(\)/);
assert.match(app, /card\.textContent\.toLowerCase\(\)\.includes\(query\)/);
assert.match(app, /partFilter\.addEventListener\("input", filterParts\)/);
assert.match(app, /budgetAllocation\[type\]\.percentage/);
assert.match(html, /id="constraint-chips" aria-label="Active build constraints"/);
assert.match(app, /function renderConstraintChips\(constraints\)/);
assert.match(app, /data-edit-field=/);
assert.match(app, /setWorkspaceView\("configure"\)/);
assert.match(html, /id="results-freshness" role="status" aria-live="polite">Up to date/);
assert.match(app, /function setResultStale\(stale\)/);
assert.match(app, /Inputs changed · refresh needed/);
assert.match(app, /optimizeLabel\.textContent = stale \? "Refresh build"/);
assert.match(html, /id="action-toast" role="status" aria-live="polite"/);
assert.match(html, /id="close-toast" aria-label="Dismiss notification"/);
assert.match(app, /function showToast\(message\)/);
assert.match(app, /new MutationObserver/);
assert.match(html, /id="motion-toggle"[^>]+aria-pressed="true">Motion on/);
assert.match(app, /localStorage\.getItem\("aipo-gpt-motion"\)/);
assert.match(app, /function resetPointerEffects\(\)/);
assert.match(app, /motionToggle\.addEventListener\("click"/);
assert.equal((html.match(/data-density=/g) ?? []).length, 2);
assert.match(app, /function setResultDensity\(density/);
assert.match(app, /localStorage\.getItem\("aipo-gpt-density"\)/);
assert.match(app, /resultsPanel\.dataset\.density = safeDensity/);
assert.match(html, /id="command-trigger"[^>]+aria-haspopup="dialog"/);
assert.match(html, /<dialog class="command-dialog" id="command-dialog"/);
assert.equal((html.match(/data-command=/g) ?? []).length, 10);
assert.match(app, /function openCommandDialog\(\)/);
assert.match(app, /function runCommand\(command\)/);
assert.match(app, /event\.metaKey \|\| event\.ctrlKey/);
assert.match(app, /commandSearch\.addEventListener\("input"/);
assert.equal((html.match(/data-result-target=/g) ?? []).length, 3);
assert.match(html, /id="build-metrics" tabindex="-1"/);
assert.match(html, /id="component-stack" tabindex="-1"/);
assert.match(html, /id="validation-details" tabindex="-1"/);
assert.match(app, /target\.scrollIntoView/);
assert.match(app, /function setActiveResultSection\(sectionId\)/);
assert.match(app, /new IntersectionObserver/);
assert.match(app, /button\.setAttribute\("aria-current", "location"\)/);
assert.match(css, /\.result-jump-nav button\.is-active/);
assert.match(css, /\.command-list button\[hidden\] \{ display: none; \}/);
assert.match(app, /function animateMetric\(element, nextValue, formatter\)/);
assert.match(app, /dataset\.metricValue/);
assert.match(app, /performance\.now\(\)/);
assert.match(app, /animateMetric\(document\.querySelector\("#total-price"\)/);
assert.match(html, /id="result-deltas"[^>]+aria-live="polite" hidden/);
assert.match(app, /function renderRecommendationDeltas\(previous, current\)/);
assert.match(app, /current\.upgradeReadiness\.score - previous\.upgradeReadiness\.score/);
assert.match(app, /renderRecommendationDeltas\(baselineRecommendation \?\? previousRecommendation, recommendation\)/);
assert.match(app, /button\.tabIndex = isActive \? 0 : -1/);
assert.match(app, /\["ArrowRight", "ArrowDown"\]\.includes\(event\.key\)/);
assert.match(app, /event\.key === "Home"/);
assert.match(app, /profileButtons\[nextIndex\]\.click\(\)/);
assert.match(app, /commandDialog\.addEventListener\("keydown"/);
assert.match(app, /commandButtons\.filter\(\(button\) => !button\.hidden\)/);
assert.match(app, /visibleCommands\.at\(-1\)\.focus\(\)/);
assert.match(app, /document\.activeElement === commandSearch/);
assert.match(app, /querySelectorAll\("\.metric"\)/);
assert.match(app, /getBoundingClientRect\(\)/);
assert.match(app, /--metric-tilt-x/);
assert.match(app, /--metric-tilt-y/);
assert.match(html, /Press <kbd>⌘<\/kbd>\/<kbd>Ctrl<\/kbd> \+ <kbd>Enter<\/kbd> to generate/);
assert.match(app, /form\.addEventListener\("keydown"/);
assert.match(app, /event\.key === "Enter"/);
assert.match(app, /form\.reportValidity\(\)/);
assert.match(app, /form\.requestSubmit\(\)/);
assert.match(html, /id="focus-toggle"[^>]+aria-pressed="false">Focus mode/);
assert.match(app, /function setFocusMode\(enabled\)/);
assert.match(app, /event\.key === "Escape" && root\.dataset\.focus === "on"/);
assert.match(app, /command === "focus-mode"/);
assert.match(html, /id="contrast-toggle"[^>]+aria-pressed="false">High contrast/);
assert.match(app, /function setContrastMode\(enabled/);
assert.match(app, /localStorage\.getItem\("aipo-gpt-contrast"\)/);
assert.match(css, /html\[data-contrast="high"\]/);
assert.match(html, /id="pin-baseline">Pin current build/);
assert.match(html, /id="clear-baseline" hidden>Clear baseline/);
assert.match(app, /baselineRecommendation = latestRecommendation/);
assert.match(app, /baselineRecommendation \?\? previousRecommendation/);
assert.match(app, /Comparison baseline pinned/);
assert.match(app, /data-copy-part="\$\{type\}"/);
assert.match(app, /event\.target\.closest\("\[data-copy-part\]"\)/);
assert.match(app, /navigator\.clipboard\.writeText\(text\)/);
assert.match(app, /details copied/);
assert.match(html, /id="revert-inputs" disabled>Revert inputs/);
assert.match(app, /latestFormState = \{ goal: fields\.goal\.value/);
assert.match(app, /revertInputsButton\.addEventListener\("click"/);
assert.match(app, /Inputs restored to the visible recommendation/);
assert.match(html, /id="changed-fields" hidden/);
assert.match(html, /id="changed-fields-list" aria-label="Changed inputs"/);
assert.match(app, /function renderChangedFields\(\)/);
assert.match(app, /data-restore-field="\$\{key\}"/);
assert.match(app, /setResultStale\(renderChangedFields\(\) > 0\)/);
assert.match(html, /Swipe left or right to move between setup and results/);
assert.match(app, /workspace\.addEventListener\("pointerdown"/);
assert.match(app, /event\.pointerType !== "touch"/);
assert.match(app, /Math\.abs\(horizontal\) < 80/);
assert.match(app, /horizontal < 0 \? "results" : "configure"/);
assert.match(html, /id="mobile-primary-action" data-action="generate">Generate recommendation/);
assert.match(app, /mobilePrimaryAction\.dataset\.action = view === "configure" \? "generate" : "edit"/);
assert.match(app, /mobilePrimaryAction\.addEventListener\("click"/);
assert.match(css, /\.mobile-action-bar \{ position: fixed/);
assert.match(html, /id="metric-guide-trigger"[^>]+aria-haspopup="dialog"/);
assert.match(html, /<dialog class="metric-guide-dialog" id="metric-guide-dialog"/);
assert.match(html, /<dt>PSU reserve<\/dt>/);
assert.match(app, /command === "metric-guide"/);
assert.match(app, /metricGuideDialog\.showModal\(\)/);
assert.match(html, /<summary>Recent builds <span id="recent-build-count">0<\/span><\/summary>/);
assert.match(html, /id="recent-build-list"/);
assert.match(app, /sessionStorage\.getItem\(RECENT_BUILDS_KEY\)/);
assert.match(app, /function recordRecentBuild\(recommendation, constraints\)/);
assert.match(app, /data-recent-build="\$\{index\}"/);
assert.match(app, /Restored \$\{entry\.profileLabel\.toLowerCase\(\)\} build/);
assert.match(html, /id="shortcut-trigger"[^>]+aria-haspopup="dialog"/);
assert.match(html, /<dialog class="shortcut-dialog" id="shortcut-dialog"/);
assert.match(app, /command === "shortcut-guide"/);
assert.match(app, /event\.key === "\?"/);
assert.match(app, /shortcutDialog\.showModal\(\)/);

console.log("UI contract tests passed");
