import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
const app = await readFile(new URL("../dist/app.js", import.meta.url), "utf8");

for (const profile of ["balanced", "performance", "value"]) {
  assert.match(html, new RegExp(`data-profile="${profile}"`));
}

assert.equal((html.match(/class="profile-button/g) ?? []).length, 3);
assert.match(html, /role="group" aria-label="Recommendation profile"/);
assert.match(app, /recommendBuild\(constraints, activeProfile\)/);
assert.match(app, /setAttribute\("aria-pressed"/);
assert.match(app, /recommendation\.rationales\[type\]/);
assert.match(html, /shows why each component earned its place/);
assert.match(html, /id="copy-build"/);
assert.match(html, /id="copy-link"/);
assert.match(html, /id="download-build"/);
assert.match(html, /id="print-build"/);
assert.match(html, /id="export-status" role="status" aria-live="polite"/);
assert.match(app, /navigator\.clipboard\.writeText/);
assert.match(app, /new Blob/);
assert.match(app, /window\.print\(\)/);
assert.match(html, /<summary>Compare all profiles<\/summary>/);
assert.match(html, /id="profile-comparison-body"/);
assert.match(app, /data-compare-profile/);
assert.match(app, /button\.dataset\.compareProfile/);
assert.match(html, /id="upgrade-readiness"/);
assert.match(app, /recommendation\.upgradeReadiness\.label/);
assert.match(html, /id="cooler-noise"/);
assert.match(app, /recommendation\.acoustics\.decibels/);
assert.match(html, /id="power-reserve"/);
assert.match(app, /recommendation\.powerReserve\.percentage/);
assert.match(html, /id="goal"[^>]+required minlength="12"/);
assert.match(html, /id="budget"[^>]+required/);
assert.match(html, /id="form-error" role="alert"/);
assert.match(app, /form\.addEventListener\("invalid"/);
assert.equal((html.match(/data-preset=/g) ?? []).length, 3);
assert.match(app, /fields\.goal\.value = button\.dataset\.preset/);
assert.match(app, /history\.replaceState/);
assert.match(app, /restoreFromUrl\(syncGoalToFields\(\)\)/);
assert.match(app, /window\.location\.href/);
assert.match(html, /class="skip-link" href="#optimizer-form"/);
assert.match(html, /id="results-heading" tabindex="-1"/);
assert.match(html, /id="result-status" role="status" aria-live="polite"/);
assert.match(app, /render\(syncGoalToFields\(\), \{ announce: true \}\)/);
assert.match(app, /querySelector\("#results-heading"\)\.focus\(\)/);
assert.match(html, /<summary>Where the budget goes<\/summary>/);
assert.match(html, /id="allocation-list"/);
assert.match(app, /recommendation\.budgetAllocation/);
assert.match(html, /id="shortfall-panel" hidden/);
assert.match(html, /id="shortfall-list"/);
assert.match(app, /recommendation\.shortfalls/);
assert.match(html, /<option value="development">Software development<\/option>/);
assert.match(html, /id="build-id"/);
assert.match(app, /latestRecommendation\.buildId/);
assert.match(html, /id="search-stats"/);
assert.match(app, /recommendation\.searchStats\.evaluated/);
assert.match(html, /<summary>Runner-up configurations<\/summary>/);
assert.match(html, /id="alternatives-list"/);
assert.match(app, /recommendation\.alternatives/);
assert.match(app, /alternative\.platformWatts/);
assert.match(app, /alternative\.goalsMet/);
assert.match(html, /id="balance-score"/);
assert.match(app, /recommendation\.componentBalance\.score/);
assert.match(html, /id="reset-build"/);
assert.match(app, /DEFAULT_STATE = Object\.freeze/);
assert.match(app, /Optimizer defaults restored/);
assert.match(app, /fields\.goal\.focus\(\)/);
assert.match(html, /id="recovery-path" hidden/);
assert.match(app, /recommendation\.goalRecovery/);
assert.match(app, /meeting every performance target/);

console.log("UI contract tests passed");
